name: youtube-analysis
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - google-auth
  - google-auth-oauthlib
  - cryptography
  - statsmodels
  - pillow
  - ipykernel 